[profile.default]
src = 'contracts'
out = 'foundry-out'
libs = ['lib']
gas_reports = ["*"]
viaIR = true
solc_version = '0.8.24'
evm_version = "cancun"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config